# Generated by Django 5.0.6 on 2024-06-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verificationCodeExpiresAt',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
